version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: npm install
      # LINT
      # TEST
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud auth list

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          #filters:
          #  branches:
          #    only: master